import { cn } from "@/lib/utils";

/**
 * A red nine-pointed star ("seal") that sits on the corner of a book cover and
 * shows the discount percentage. Pure SVG — the nine points are generated by
 * alternating an outer and inner radius around the centre.
 */
export function DiscountBadge({
  percent,
  className,
}: {
  percent: number;
  className?: string;
}) {
  const points = starPoints(9, 50, 50, 49, 39);

  return (
    <div className={cn("pointer-events-none absolute z-10", className)} aria-hidden="true">
      <svg viewBox="0 0 100 100" className="h-full w-full drop-shadow-md">
        <polygon points={points} fill="#e11d2a" stroke="#b3121d" strokeWidth="1.5" />
        <text
          x="50"
          y="50"
          textAnchor="middle"
          dominantBaseline="central"
          fill="#ffffff"
          fontWeight="800"
          fontSize="30"
          fontFamily="Arial, sans-serif"
        >
          -{percent}%
        </text>
      </svg>
    </div>
  );
}

/** Build the polygon points for an N-pointed star. */
function starPoints(
  spikes: number,
  cx: number,
  cy: number,
  outer: number,
  inner: number
): string {
  const step = Math.PI / spikes;
  const coords: string[] = [];
  let rot = -Math.PI / 2; // start at the top
  for (let i = 0; i < spikes * 2; i++) {
    const r = i % 2 === 0 ? outer : inner;
    coords.push(`${(cx + Math.cos(rot) * r).toFixed(2)},${(cy + Math.sin(rot) * r).toFixed(2)}`);
    rot += step;
  }
  return coords.join(" ");
}
